<script setup lang="ts">
import { computed, ref } from 'vue'
import { RouterLink, useRoute } from 'vue-router'
import { topics } from '../content'
import { useAppStore } from '../stores/app'
import { speak, stopSpeaking } from '../services/speech'
const store = useAppStore(); const route = useRoute(); const lesson = computed(() => topics.flatMap(topic => topic.lessons).find(item => item.id === route.params.id)); const isPlaying = ref(false)
const play = () => { if (!lesson.value) return; isPlaying.value = speak(`Khẩu quyết: ${lesson.value.mnemonic}. ${lesson.value.steps.map((step, i) => `Bước ${i + 1}: ${step.text}`).join('. ')}`) }
const stop = () => { stopSpeaking(); isPlaying.value = false }
const complete = () => { if (lesson.value) store.toggleComplete(lesson.value.id) }
</script>
<template><div v-if="lesson" class="lesson-detail"><RouterLink :to="`/topics/${lesson.topicId}`" class="back-link">← Quay lại chuyên đề</RouterLink><div class="lesson-meta"><span class="risk" :class="lesson.risk">{{ lesson.risk === 'high' ? 'Cần chú ý' : 'Thực hành' }}</span><span>{{ lesson.minutes }} phút</span><span>Độ khó {{ lesson.difficulty }}/5</span></div><h1>{{ lesson.title }}</h1><p class="lead">{{ lesson.summary }}</p><div class="mnemonic"><span>NHỚ NHANH</span><strong>“{{ lesson.mnemonic }}”</strong></div><div class="diagram" aria-label="Sơ đồ minh họa quỹ đạo xe"><div class="lane" /><div class="diagram-car">↗</div><span class="diagram-label">QUỸ ĐẠO AN TOÀN</span></div><div class="tts-bar"><div><strong>Nghe hướng dẫn</strong><small>Không cần nhìn màn hình</small></div><button class="button dark" @click="isPlaying ? stop() : play()">{{ isPlaying ? '■ Dừng' : '▶ Đọc to' }}</button></div><section><div class="section-head"><div><p class="eyebrow">LÀM THEO TỪNG BƯỚC</p><h2>Quy trình</h2></div></div><ol class="steps"><li v-for="(step, index) in lesson.steps" :key="step.id"><span>{{ index + 1 }}</span><p>{{ step.text }}</p><button class="step-speak" :aria-label="`Đọc bước ${index + 1}`" @click="speak(`Bước ${index + 1}: ${step.text}`)">🔊</button></li></ol></section><div class="info-grid"><div class="info-box warning"><span>!</span><div><strong>Lỗi hay gặp</strong><ul><li v-for="mistake in lesson.mistakes" :key="mistake">{{ mistake }}</li></ul></div></div><div class="info-box recovery"><span>↻</span><div><strong>Nếu lỡ sai</strong><p>{{ lesson.recovery }}</p></div></div></div><div class="safety"><strong>Ưu tiên an toàn</strong><p>{{ lesson.safety }}</p></div><button class="button primary full" @click="complete">{{ store.completed.includes(lesson.id) ? '✓ Đã nắm bài này' : 'Đánh dấu đã nắm' }}</button></div><div v-else class="empty">Không tìm thấy bài học.</div></template>
